---
- hosts: all
  become: true
  become_user: root
  tasks:
  - apt:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - yum:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    when:
    - ansible_distribution != 'Debian'
    - ansible_distribution != 'Ubuntu'
    - ansible_distribution != 'CentOS'
    - ansible_distribution != 'Red Hat Enterprise Linux'
