---
- apt:
    name: apt
    state: present
  notify: Apt Was Missing
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- template:
    src: ../templates/config.j2
    dest: /tmp/config
    owner: root
    group: root
    mode: 0600

- copy:
    src: ../files/service.sh
    dest: /tmp/service.sh
    owner: root
    group: root
    mode: 0755
